package Mighty::Social::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Mighty::Social::Schema',
    
    
);

=head1 NAME

Mighty::Social::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Mighty::Social>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Mighty::Social::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Adam Taylor

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
