#!/usr/bin/env perl

use FindBin::libs;

use Mighty::Social;
use DBIx::Class::Migration::Script;
 
DBIx::Class::Migration::Script->run_with_options(
    schema => Mighty::Social->model('Schema')->schema
);
